// File automatically generated by swift-bridge.
typedef struct AudioBuffer AudioBuffer;
void __swift_bridge__$AudioBuffer$_free(void* self);

void* __swift_bridge__$Vec_AudioBuffer$new(void);
void __swift_bridge__$Vec_AudioBuffer$drop(void* vec_ptr);
void __swift_bridge__$Vec_AudioBuffer$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_AudioBuffer$pop(void* vec_ptr);
void* __swift_bridge__$Vec_AudioBuffer$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_AudioBuffer$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_AudioBuffer$len(void* vec_ptr);
void* __swift_bridge__$Vec_AudioBuffer$as_ptr(void* vec_ptr);

void __swift_bridge__$add_data(void* buffer, struct __private__FfiSlice data);


